"""Generate Claude slash commands mirroring dashboard actions."""

from pathlib import Path

from .project import Project
from .roadmap import RoadmapParser

AUTO_HEADER = "<!-- Auto-generated by Claudetini. Do not edit. -->"


class SlashCommandGenerator:
    """Generate .claude/commands markdown command files."""

    def __init__(self, project: Project):
        self.project = project
        self.commands_dir = project.path / ".claude" / "commands"
        self.commands_dir.mkdir(parents=True, exist_ok=True)

    def generate(self) -> list[Path]:
        """Generate all default command files."""
        roadmap = RoadmapParser.parse(self.project.path)
        next_item = None
        progress = "No roadmap found."
        if roadmap:
            nxt = roadmap.find_next_incomplete()
            if nxt:
                next_item = nxt[2].text
            progress = f"{roadmap.completed_items}/{roadmap.total_items} complete ({roadmap.progress_percent:.0f}%)"

        files = {
            "next.md": self._render_next(next_item),
            "status.md": self._render_status(progress),
            "gates.md": self._render_gates(),
            "done.md": self._render_done(next_item),
        }

        written = []
        for name, content in files.items():
            path = self.commands_dir / name
            path.write_text(content)
            written.append(path)
        return written

    @staticmethod
    def _render_next(next_item: str | None) -> str:
        item = next_item or "Review roadmap and select the next actionable item."
        return "\n".join(
            [
                AUTO_HEADER,
                "",
                "# /next",
                "",
                f"Next suggested roadmap item: {item}",
                "",
                "Compose an execution plan and start implementing it.",
            ]
        )

    @staticmethod
    def _render_status(progress: str) -> str:
        return "\n".join(
            [
                AUTO_HEADER,
                "",
                "# /status",
                "",
                f"Roadmap progress: {progress}",
                "Show project health summary and latest session recap.",
            ]
        )

    @staticmethod
    def _render_gates() -> str:
        return "\n".join(
            [
                AUTO_HEADER,
                "",
                "# /gates",
                "",
                "Run quality gates (tests, lint, security scan) and report results.",
            ]
        )

    @staticmethod
    def _render_done(next_item: str | None) -> str:
        item = next_item or "current roadmap item"
        return "\n".join(
            [
                AUTO_HEADER,
                "",
                "# /done",
                "",
                f"Mark '{item}' complete if done, then show the next recommended item.",
            ]
        )

